--ORDERS 테이블의 모든 칼럼 조회
SELECT *
FROM ORDERS o 

--주문번호 (ORDER_ID)와 주문일시 (ORDER_TMS)만 조회
SELECT o.ORDER_ID, o.ORDER_TMS 
FROM ORDERS o 

--주문상태가 OPEN 인 주문만 조회
SELECT *
FROM ORDERS o 
WHERE o.ORDER_STATUS = 'COMPLETE'

--주문상태가 CANCELLED OR REFUNDED 인 주문 조회
SELECT *
FROM ORDERS o 
WHERE o.ORDER_STATUS IN ('CANCELLED','COMPLETE')


--STORE_ID 가 1인 주문중에서 주문상태가 COMPLETE 가 아닌 주문조회
SELECT *
FROM ORDERS o 
WHERE o.STORE_ID = 1 AND o.ORDER_STATUS !='COMPLETE'

--2022년 1월 1일 이후 주문된 건만 조회
SELECT *
FROM ORDERS o 
WHERE o.ORDER_TMS >= '2022-01-01'

--전체 주문을 최신 주문일시 순으로 정렬하여 조회
SELECT *
FROM ORDERS o 
WHERE o.ORDER_TMS DESC
----------------------------------------------------------08/12-------------------------------------------------------------------------
-- COTOMERS TABLE
--이름이 'K'로 시작하는 고객의 CUSTOMER_ID, FULL_NAME 조회

SELECT	c.CUSTOMER_ID, c.FULL_NAME FROM CUSTOMERS c WHERE c.FULL_NAME LIKE 'k%'


--이름이 'son'로 시작하는 고객의 CUSTOMER_ID, FULL_NAME 조회
SELECT	c.CUSTOMER_ID, c.FULL_NAME FROM CUSTOMERS c WHERE c.FULL_NAME LIKE '%son'

--이메일에서 '@' 앞부분(아이디) 추출하기
SELECT c.CUSTOMER_ID, c.FULL_NAME SUBSTR(C.EMAIL_ADDRESS,1,INSTR(C.EMAIL_ADDRESS,'@')-1) AS EMAIL_ID	
WHERE c.EMAIL_ADDRESS 

--이름에서 공백 위치 찾기
SELECT	c.CUSTOMER_ID, c.FULL_NAME, INSTR(c.FULL_NAME ,' ') FROM CUSTOMERS c 

--이름과 이메일을 하나의 문자열로 합치기 (name(name@gmail.com)
SELECT	c.CUSTOMER_ID, c.FULL_NAME || '('|| C.EMAIL_ADDRESS ||')' AS NAME_WITH_EMAIL FROM CUSTOMERS c 

--이름 앞, 뒤 공백 제거 후 조회 (customer_id, full_name)
SELECT c.CUSTOMER_ID, TRIM(c.FULL_NAME ) FROM CUSTOMERS c 

--customer_id를 5자리로, 빈자리는 0으로 채우기
SELECT c.CUSTOMER_ID, LPAD(c.FULL_NAME,5,'0') FROM CUSTOMERS c 

--PRODUCTS 테이블
--상품명에 'Shirt'가 포함된 상품정보조회
SELECT * FROM PRODUCTS p  WHERE p.PRODUCT_NAME LIKE '%Shirt%'

--상품명에 'Boy'로 시작하는 상품정보조회
SELECT * FROM PRODUCTS p  WHERE p.PRODUCT_NAME LIKE 'Boy%'

-- 상품명 앞 10글자만 추출 후 short_name 칼럼명으로 추출
SELECT p.PRODUCT_ID, SUBSTR(p.PRODUCT_NAME,1,10) AS SHORT_NAME FROM PRODUCTS p  

--상품명 20자 초과시 앞 20자 + '...' CASE~WHEN 사용(칼럼명 DISPLAY_NAME)
SELECT p.PRODUCT_ID,
	CASE 
		WHEN LENGTH(p.PRODUCT_NAME) > 20 THEN SUBSTR(P.PRODUCT_NAME,1,20)||'...'
		ELSE p.PRODUCT_NAME
	END AS DISPLAY_NAME
FROM PRODUCTS p 

--상품명 길이가 짝수/홀수 인 상품 구분 
--PRODUCT_ID, NAME, 상품명 길이(NAME_LEN으로 지정)
--짝수, 홀수 컬렴명은 LEN_TYPE 으로 지정
-- CASE~ WHEN 사용
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, LENGTH(p.PRODUCT_NAME) AS NAME_LEN,
	CASE 
		WHEN MOD(LENGTH(p.PRODUCT_NAME),2) = 0 THEN '짝수'
		ELSE '홀수'
	END AS LEN_TYPE
FROM PRODUCTS p 

--STORE 테이블
-- WEB_ADDRESS 가 NULL 이 아니면서 'Https'로 시작하는 매장 조회
-- store_id, store_name, web_address 조회
SELECT s.STORE_ID, s.STORE_NAME, s.WEB_ADDRESS  
FROM STORES s 
WHERE s.WEB_ADDRESS IS NOT NULL AND s.WEB_ADDRESS LIKE 'https%' 

-- ORDERS 테이블
-- ORDER_ID를 'ORD-00001'형태로
-- ORDER_ID,'ORD-00001' (ORDER_CODE 컬럼명 사용) 추출

SELECT o.ORDER_ID, 'ORD-' || LPAD(o.ORDER_ID,5,'0') AS ORDER_CODE 
FROM ORDERS o 
------------------------------------------------------------------------------08/13---------------------------------------------------------

-- 모든 주문에 대해 주문한 고객의 이름을 함께 출력
SELECT O.*, C.FULL_NAME
FROM ORDERS o JOIN CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID 


-- 모든 주문에 대해 주문이 발생한 매장 이름(STORE_NAME)을 함께 조회
SELECT S.STORE_NAME 
FROM ORDERS o  JOIN STORES s 
ON o.STORE_ID = s.STORE_ID

--모든 주문상세(ORDER_ITEMS)에 대해 상품명(PRODUCT_NAME) 조회
SELECT oi.*,p.PRODUCT_NAME 
FROM ORDER_ITEMS oi JOIN PRODUCTS p  
ON p.PRODUCT_ID = oi.PRODUCT_ID

--모든 배송에 대해 배송받는 고객의 이름 조회
SELECT c.FULL_NAME, s.DELIVERY_ADDRESS 
FROM CUSTOMERS c JOIN SHIPMENTS s ON c.CUSTOMER_ID = s.CUSTOMER_ID 

-- 다중연결(3개)
-- 재고(Inventory_table)+매장이름+상품명 조회

SELECT i.PRODUCT_INVENTORY, s.STORE_NAME, p.PRODUCT_NAME 
FROM INVENTORY i JOIN PRODUCTS p  ON i.PRODUCT_ID = p.PRODUCT_ID  
				JOIN  STORES s  ON i.STORE_ID = s.STORE_ID

-- 고객이름, 주문일시, 매장이름 조회
SELECT c.FULL_NAME,s.STORE_NAME, o.ORDER_TMS 
FROM ORDERS o JOIN CUSTOMERS c  ON c.CUSTOMER_ID = o.CUSTOMER_ID
			JOIN STORES s  ON o.STORE_ID = s.STORE_ID 

-- 각 주문 상세건에 대해 고객이름, 상품명, 수량을 조회
SELECT c.FULL_NAME, O.ORDER_TMS , OI.QUANTITY, p.PRODUCT_NAME 
FROM ORDERS o JOIN CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
			JOIN ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
			JOIN PRODUCTS p  ON oi.PRODUCT_ID = p.PRODUCT_ID

-- 각 배송 건에 대해 고객이름, 배송지, 매장이름 조회
SELECT c.FULL_NAME, s.DELIVERY_ADDRESS, s2.STORE_NAME 
FROM CUSTOMERS c JOIN SHIPMENTS s  ON c.CUSTOMER_ID = s.CUSTOMER_ID
				JOIN STORES s2  ON s.STORE_ID = s2.STORE_ID
			
-- 각 주문 상세건에 대해 상품명과 그상품을 실제로 배송한 배송상태(shipment_status)조회
SELECT oi.ORDER_ID , p.PRODUCT_NAME, s.SHIPMENT_STATUS 
FROM ORDER_ITEMS oi JOIN PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
					JOIN SHIPMENTS s ON oi.SHIPMENT_ID = s.SHIPMENT_ID



--LEFT JOIN
-- 한 번도 주무하지 않은 고객이 있는지 조회(CUSTORMERS/ORDERS)

SELECT * 
FROM CUSTOMERS c LEFT JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE o.ORDER_ID IS NULL

-- 아직 배송 정보가 없는 주문상세 건 조회 (ORDER_ITEMS/SHIPMENTS)
SELECT oI.ORDER_ID, oi.PRODUCT_ID, s.SHIPMENT_ID  
FROM ORDER_ITEMS oi  LEFT JOIN SHIPMENTS s ON OI.SHIPMENT_ID = S.SHIPMENT_ID 
WHERE s.SHIPMENT_ID IS NULL

-- 어떤 매장에도 배송된 적 없는 고객 정보 조회(CUSTORMERS/SHIPMENTS)

SELECT c.CUSTOMER_ID, c.FULL_NAME  
FROM CUSTOMERS c LEFT JOIN SHIPMENTS s ON c.CUSTOMER_ID = s.CUSTOMER_ID
WHERE s.SHIPMENT_ID IS NULL

-- 고객별 총 주문건수 고객아이디,이름,건수 + SUM(), COUNT()

SELECT c.CUSTOMER_ID, c.FULL_NAME, COUNT(o.ORDER_ID) 
FROM CUSTOMERS c JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID 
GROUP BY c.CUSTOMER_ID, c.FULL_NAME 
ORDER BY c.CUSTOMER_ID 

-- 매장별 재고 등록 상품 수와 총 재고 수량

SELECT s.STORE_ID, s.STORE_NAME, COUNT(i.PRODUCT_ID) AS PRODUCT_COUNT, SUM(i.PRODUCT_INVENTORY) AS TOTAL_INVENTORY
FROM STORES s JOIN INVENTORY i ON s.STORE_ID = i.STORE_ID
GROUP BY s.STORE_ID, s.STORE_NAME 
ORDER BY s.STORE_ID 

-- 고객별 총 구매금액(UNIT_PRICE*QUANTITY)을 구하고 금액이 높은 순으로 정렬

SELECT c.CUSTOMER_ID, c.FULL_NAME, SUM(OI.QUANTITY *OI.UNIT_PRICE) AS TOTAL_AMOUNT
FROM CUSTOMERS c JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID JOIN ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
GROUP BY c.CUSTOMER_ID, c.FULL_NAME
ORDER BY TOTAL_AMOUNT DESC
-- 매장별 매출 순위 조회(STORE + ORDERS + ORDER_ITEMS)

SELECT S.STORE_ID , S.STORE_NAME , SUM(OI.QUANTITY *OI.UNIT_PRICE) AS TOTAL_AMOUNT
FROM ORDERS o JOIN CUSTOMERS c ON C.CUSTOMER_ID = O.CUSTOMER_ID 
			JOIN ORDER_ITEMS oi ON OI.ORDER_ID  = O.ORDER_ID 
			JOIN STORES s ON S.STORE_ID  = O.STORE_ID 
GROUP BY S.STORE_ID , S.STORE_NAME
ORDER BY TOTAL_AMOUNT DESC


----------------------------------------------------------------------------------------------8/14-----------------------------------------------------------------------------------------------------

-- 서브쿼리
-- 전체 상품의 평균단가보다 비싼 상품 조회

SELECT * FROM PRODUCTS p  WHERE p.UNIT_PRICE   >(SELECT AVG(p.UNIT_PRICE) )FROM PRODUCTS p2 ) 

--각 상품에 대해 전체 평균단가와의 차액을 함께 조회(SELECT 절 서브쿼리)

SELECT p.PRODUCT_ID,p.PRODUCT_IMAGE, p.UNIT_PRICE,p.UNIT_PRICE -(SELECT AVG(p.UNIT_PRICE) FROM PRODUCTS p ) AS DIFF FROM PRODUCTS p 

--가장 최근에 주문한 건의 주문 정보 조회

SELECT * FROM ORDERS o WHERE o.ORDER_TMS =(SELECT MAX(o.ORDER_TMS ) FROM ORDERS o )

--도쿄지역 매장에서 발생한 주문만 조회
--ORDERS의 STORE_ID가 서브쿼리 결과 IN 인 경우

SELECT * FROM ORDERS o  WHERE o.STORE_ID IN(SELECT s.STORE_ID  FROM STORES s WHERE s.PHYSICAL_ADDRESS LIKE '%Tokyo%') 

--'CANCELLED'상태인 주문을 한 번이라도 한 적 있는 고객 조회

SELECT * FROM CUSTOMERS c  WHERE c.CUSTOMER_ID IN (SELECT * FROM ORDERS o WHERE o.ORDER_STATUS ='CANCELLED')

-- 재고에 한번도 등록된 적이 없는 상품 조회

SELECT p.PRODUCT_ID ,p.PRODUCT_NAME  FROM PRODUCTS p WHERE p.PRODUCT_ID NOT IN (SELECT i.PRODUCT_ID  FROM INVENTORY i)

-- 주문을 한 번이라도 한 고객 조회(EXISTS 사용)

SELECT c.CUSTOMER_ID, c.FULL_NAME  FROM CUSTOMERS c WHERE EXISTS (SELECT 1 FROM ORDERS o WHERE c.CUSTOMER_ID = o.CUSTOMER_ID ) 

-- 재고수량이 0인 상품이 하나라도 있는 매장조회(EXISTS 사용)

SELECT s.STORE_NAME,s.STORE_ID  FROM STORES s WHERE EXISTS (SELECT 1 FROM INVENTORY i WHERE i.PRODUCT_INVENTORY =0 AND s.STORE_ID = i.STORE_ID ) 

-- 매장별 평균 상품 단가를 구하는 서브쿼리를 생성 뒤 전체 매장 평균보다 높은 매장만 다시 추출
SELECT * FROM
(SELECT S.STORE_ID, S.STORE_NAME, AVG(p.UNIT_PRICE) AS AVG_PRICE FROM STORES s JOIN INVENTORY i  ON s.STORE_ID = i.STORE_ID JOIN PRODUCTS p  ON i.PRODUCT_ID = p.PRODUCT_ID GROUP BY s.STORE_ID,S.STORE_NAME) AS STORE_AVG 
WHERE AVG_PRICE > (SELECT AVG(P.UNIT_PRICE) FROM PRODUCTS p)

-- 각 고객에 대해 가장 최근 주문일을 서브쿼리로 구하고 그 주문의 매장 이름까지 함께 조회

SELECT c.CUSTOMER_ID, c.FULL_NAME, o.ORDER_TMS, S.STORE_NAME  FROM CUSTOMERS c JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID AND o.ORDER_TMS = (SELECT MAX(o2.ORDER_TMS) FROM ORDERS o2 WHERE o2.CUSTOMER_ID = c.CUSTOMER_ID) JOIN STORES s ON o.STORE_ID = s.STORE_ID

-- 상품별 판매 순위를 매기되 판매된 적이 한 번도 없는 상품도 0건으로 함께 표시
--RANK() OVER

SELECT p.PRODUCT_ID, p.UNIT_PRICE , RANK() OVER(ORDER BY P.UNIT_PRICE DESC) 
FROM PRODUCTS p 

SELECT p.PRODUCT_ID, p.PRODUCT_NAME, NVL(SUM(oi.QUANTITY),0) AS TOTAL_SOLD, RANK() OVER(ORDER BY NVL(SUM(oi.QUANTITY),0)) AS SALES_RANK
FROM  PRODUCTS p LEFT JOIN ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID 
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME 














































